### PR TITLE
Handle null values in stats

### PR DESCRIPTION
**Pull request by hackmajoris**
The chess user may or may not have games on specific category, ex: blitz, bullet, rapid. For example, I don't have bullet's best game but have others. In this case your actions fails with nullity access error.

image

### CODE REVIEW

**Review by Balastrong — CHANGES_REQUESTED** [review]
Hey @hackmajoris, thank you for the PR!

As I can see from your screenshot, if a player does not have a specific category (say `chess_blitz`) the entire object is missing, so adding a nullish coalescing after `last` only is not enough.

To fix this you might consider also adding it already before `last` in  `stats.chess_blitz?.last?.rating`.

This would produce a table cell with an empty row,. Maybe we should add some kind of placeholder in case the value is empty? What do you think? :)

**Comment by hackmajoris** [comment]
> Hey @hackmajoris, thank you for the PR!
> 
> As I can see from your screenshot, if a player does not have a specific category (say `chess_blitz`) the entire object is missing, so adding a nullish coalescing after `last` only is not enough.
> 
> To fix this you might consider also adding it already before `last` in `stats.chess_blitz?.last?.rating`.
> 
> This would produce a table cell with an empty row,. Maybe we should add some kind of placeholder in case the value is empty? What do you think? :)

I've added a simple text placeholder. You can adjust it if you have something in mind.

**Comment by Balastrong** [comment]
`No Rating` is fine :)

Looks good to me, thank you again! 😄

**Review by Balastrong — APPROVED** [review]

**Comment by hackmajoris** [comment]
@Balastrong Could you publish a new Github Action Version with the latest fixes? Otherwise, I still have the same old issue. 🙃

**Comment by Balastrong** [comment]
If you set `Balastrong/chess-stats-action@main` in the actions config it will run the version currently on the `main` branch, as you can see in the [docs](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-branches-for-release-management).

I just noticed you can even reference to a commit hash 😄

**Comment by Balastrong** [comment]
Ah wait, we might have forgot something, I added them in #13 

Can you please run again the action `Balastrong/chess-stats-action@main` on your repository?

**Pull request merged**
